//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_items
    {
        public int DC_item_ID { get; set; }
        public Nullable<int> DC_invoice_ID { get; set; }
        public Nullable<int> item_Code { get; set; }
        public Nullable<int> quantity { get; set; }
        public string desc_ { get; set; }
    
        public virtual DC_invoice DC_invoice { get; set; }
    }
}
