//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.general_sales_items = new HashSet<general_sales_items>();
            this.PO_items = new HashSet<PO_items>();
            this.quotation_items = new HashSet<quotation_items>();
            this.ST_invoice = new HashSet<ST_invoice>();
            this.User_item = new HashSet<User_item>();
        }
    
        public int item_code { get; set; }
        public string item_name { get; set; }
        public Nullable<int> item_category_code { get; set; }
        public Nullable<int> item_brand_code { get; set; }
        public string item_desc { get; set; }
        public Nullable<int> unit_price { get; set; }
        public string measured_in { get; set; }
        public string size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<general_sales_items> general_sales_items { get; set; }
        public virtual item_brand item_brand { get; set; }
        public virtual item_category item_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_items> PO_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quotation_items> quotation_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_invoice> ST_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_item> User_item { get; set; }
    }
}
