//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO()
        {
            this.DC_invoice = new HashSet<DC_invoice>();
            this.general_sales_Invoice = new HashSet<general_sales_Invoice>();
            this.PO_items = new HashSet<PO_items>();
            this.ST_invoice = new HashSet<ST_invoice>();
        }
    
        public int PO_code { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> quotation_code { get; set; }
        public Nullable<System.DateTime> PO_date { get; set; }
        public Nullable<int> order_ID { get; set; }
        public string PO_desc { get; set; }
        public string shipping_address { get; set; }
        public Nullable<System.DateTime> shipping_datetime { get; set; }
        public Nullable<bool> isfrieghtonBoard { get; set; }
    
        public virtual db_User db_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_invoice> DC_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<general_sales_Invoice> general_sales_Invoice { get; set; }
        public virtual system_order system_order { get; set; }
        public virtual quotation quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_items> PO_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_invoice> ST_invoice { get; set; }
    }
}
