//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_items
    {
        public int PO_item_code { get; set; }
        public Nullable<int> PO_code { get; set; }
        public Nullable<int> item_code { get; set; }
        public string desc_ { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> cost_of_frieght { get; set; }
    
        public virtual item item { get; set; }
        public virtual PO PO { get; set; }
    }
}
