//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_items
    {
        public int ST_item_ID { get; set; }
        public Nullable<int> ST_Invoice_ID { get; set; }
        public Nullable<int> item_code { get; set; }
        public Nullable<int> values_of_good { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> sales_tax { get; set; }
        public string desc_ { get; set; }
    
        public virtual ST_invoice ST_invoice { get; set; }
    }
}
