//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public system_order()
        {
            this.POes = new HashSet<PO>();
        }
    
        public int order_code { get; set; }
        public Nullable<int> customer_user_ID { get; set; }
        public Nullable<int> supplier_user_ID { get; set; }
        public string desc_ { get; set; }
        public Nullable<System.DateTime> start_order_date { get; set; }
        public Nullable<System.DateTime> end_order_date { get; set; }
        public string commpletion_percentage { get; set; }
    
        public virtual db_User db_User { get; set; }
        public virtual db_User db_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO> POes { get; set; }
    }
}
